const data = {
    products: [
      {
        name: 'Iphone 13 Pro Max',
        slug: 'iphone-13-pro',
        category: 'Shirts',
        image: 'https://cdn1.smartprix.com/rx-ieGGhVev5-w420-h420/apple-iphone-13-pro.webp', // 679px × 829px
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality shirt',
      },
      {
        name: 'Oneplus 10R',
        slug: 'oneplus-10-r',
        category: 'Shirts',
        image: 'https://cdn1.smartprix.com/rx-iSpYPS7vY-w420-h420/oneplus-10-pro-5g-12.webp',
        price: 250,
        countInStock: 20,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        name: 'Samsung S20 Ultra',
        slug: 'samsung-s20-ultra',
        category: 'Pants',
        image: 'https://cdn1.smartprix.com/rx-i8oIG6tuO-w420-h420/samsung-galaxy-s22-u.webp',
        price: 25,
        countInStock: 15,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        name: 'Sony Xperia 1 IV',
        slug: 'sony-xperia-iv',
        category: 'Pants',
        image: 'https://cdn1.smartprix.com/rx-iL7Qnjhu8-w420-h420/sony-xperia-1-iv-12g.webp',
        price: 65,
        countInStock: 5,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
    ],
  };
  export default data;